# Generated by Django 5.2.2 on 2025-10-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='priority',
        ),
    ]
